### ISSUE TITLE
Dogu installation not concurrency safe

### ISSUE THREAD

**Issue by ppxl** [cloudogu/k8s-dogu-operator#115]
Dogus must be installed by means of a Dogu CR. If such a Dogu CR is changed during the dogu installation, chances are high that after the dogu operator fails to write the dogu resource status because of a concurrent modification.

Reproduce:
1. Have CES cluster with dogu operator <= 0.34.0
2. install new dogu with dogu CR
```
apiVersion: k8s.cloudogu.com/v1
kind: Dogu
metadata:
  name: nexus
  labels:
    app: ces
spec:
  name: official/nexus
  version: 3.52.0-1
  resources:
    dataVolumeSize: 5Gi
```
3. update dogu CR immediatly after submitting the new CR (mind the `additionalIngressAnnotations` field)
```
apiVersion: k8s.cloudogu.com/v1
kind: Dogu
metadata:
  name: nexus
  labels:
    app: ces
spec:
  name: official/nexus
  version: 3.52.0-1
  resources:
    dataVolumeSize: 5Gi
  additionalIngressAnnotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
```

Observe error in dogu operator logs: something along the lines that the K8s API fails to update dogu status. Also the dogu status is still in `installing`
